name: Deploy to Azure Storage Static Website

on:
  push:
    branches: [ "master", "main" ]  # trigger on your default branch
  workflow_dispatch: {}              # allow manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Upload everything in the repo root to the $web container
      - name: Upload to $web
        uses: azure/cli@v2
        with:
          inlineScript: |
            set -e
            az storage blob upload-batch \
              --account-name "${{ secrets.AZ_STORAGE_ACCOUNT }}" \
              --account-key  "${{ secrets.AZ_STORAGE_KEY }}" \
              --destination  "${{ secrets.AZ_STORAGE_CONTAINER }}" \
              --source "." \
              --overwrite true
